### ISSUE TITLE
Lower target framework version

### ISSUE THREAD

**Issue by gambrose** [dustinchilson/PrometheusNet.Owin#1]
prometheus-net is build against net40 but your library is using net452.

This means that I can't use the published nuget as I am targeting net451

**Comment by dustinchilson** [comment]
@gambrose Sorry, I didn't see this until now.

I've dropped the lib to net45 for you.

FYI .net 4.5[.1] is no longer supported by Microsoft, https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/
